<template>
  <div class="p-6">
    <div class="flex justify-between mb-3">
      <div class="flex justify-center items-center">
        <h5
          class="text-xl font-bold leading-none text-gray-900 dark:text-white pe-1"
        >
          Species Biodiversity
        </h5>
        <svg
          data-popover-target="chart-info"
          data-popover-placement="bottom"
          class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 20 20"
        >
          <path
            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z"
          />
        </svg>
        <div
          data-popover
          id="chart-info"
          role="tooltip"
          class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
        >
          <div class="p-3 space-y-2">
            <h3 class="font-semibold text-gray-900 dark:text-white">
              Activity growth - Incremental
            </h3>
            <p>
              Report helps navigate cumulative growth of community activities.
              Ideally, the chart should have a growing trend, as stagnating
              chart signifies a significant decrease of community activity.
            </p>
            <h3 class="font-semibold text-gray-900 dark:text-white">
              Calculation
            </h3>
            <p>
              For each date bucket, the all-time volume of activities is
              calculated. This means that activities in period n contain all
              activities up to period n, plus the activities generated by your
              community in period.
            </p>
            <a
              href="#"
              class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline"
              >Read more
              <!-- <svg
                class="w-2 h-2 ms-1.5 rtl:rotate-180"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 6 10"
              >
                <path
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="m1 9 4-4-4-4"
                /></svg
            > -->
            </a>
          </div>
          <div data-popper-arrow></div>
        </div>
      </div>
      <div>
        <button
          type="button"
          data-tooltip-target="data-tooltip"
          data-tooltip-placement="bottom"
          class="hidden sm:inline-flex items-center justify-center text-gray-500 w-8 h-8 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm"
        >
          <svg
            class="w-3.5 h-3.5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 16 18"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M8 1v11m0 0 4-4m-4 4L4 8m11 4v3a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-3"
            />
          </svg>
          <span class="sr-only">Download data</span>
        </button>
        <div
          id="data-tooltip"
          role="tooltip"
          class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700"
        >
          Download CSV
          <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
      </div>
    </div>

    <div class="py-6" id="donut-chart"></div>
  </div>
</template>

<script setup lang="ts">
import ApexCharts from "apexcharts";
import { initFlowbite } from "flowbite";
import type { Database } from "~/types/supabase";
import { ColorsHelper } from "~/utils/color-helper";

const species = useSpecies();

const chartData = ref<any>([
  { name: "Acer platanoides", value: 35.1, color: "#1C64F2" },
  { name: "Acer saccharinum", value: 23.5, color: "#16BDCA" },
  { name: "Acer rubrum", value: 2.4, color: "#FDBA8C" },
  { name: "Acer saccharum", value: 5.4, color: "#E74694" },
]);

const formattedData = computed(() => {});
let chartRef;

const getChartOptions = () => {
  console.log(chartData.value);
  return {
    series: chartData.value.map((item: any) => item.value),
    colors: ColorsHelper.generateColors(chartData.value.length),
    chart: {
      height: 320,
      width: "100%",
      type: "donut",
    },
    stroke: {
      colors: ["transparent"],
      lineCap: "",
    },
    plotOptions: {
      pie: {
        donut: {
          labels: {
            show: true,
            name: {
              show: true,
              fontFamily: "Inter, sans-serif",
              offsetY: 20,
            },
            total: {
              showAlways: true,
              show: true,
              label: "Unique species",
              fontFamily: "Inter, sans-serif",
              formatter: function (w: any) {
                const sum = w.globals.seriesTotals.reduce((a: any, b: any) => {
                  return a + b;
                }, 0);
                return "$" + sum + "k";
              },
            },
            value: {
              show: true,
              fontFamily: "Inter, sans-serif",
              offsetY: -20,
              formatter: function (value: any) {
                return value + "k";
              },
            },
          },
          size: "80%",
        },
      },
    },
    grid: {
      padding: {
        top: -2,
      },
    },
    labels: chartData.value.map((item) => item.name),
    dataLabels: {
      enabled: false,
    },
    legend: {
      position: "bottom",
      fontFamily: "Inter, sans-serif",
    },
    yaxis: {
      labels: {
        formatter: function (value: any) {
          return value + "k";
        },
      },
    },
    xaxis: {
      labels: {
        formatter: function (value: any) {
          return value + "k";
        },
      },
      axisTicks: {
        show: false,
      },
      axisBorder: {
        show: false,
      },
    },
  };
};

function refreshData() {
  const data = formattedData.value;

  if (
    document.getElementById("donut-chart") &&
    typeof ApexCharts !== "undefined"
  ) {
    const chart = new ApexCharts(
      document.getElementById("donut-chart"),
      getChartOptions()
    );
    chart.render();
    chartRef = chart;

    // Get all the checkboxes by their class name
    const checkboxes = document.querySelectorAll(
      '#devices input[type="checkbox"]'
    );

    // Function to handle the checkbox change event
    function handleCheckboxChange(event: any, chart: any) {
      const checkbox = event.target;
      if (checkbox.checked) {
        switch (checkbox.value) {
          case "desktop":
            chart.updateSeries([15.1, 22.5, 4.4, 8.4]);
            break;
          case "tablet":
            chart.updateSeries([25.1, 26.5, 1.4, 3.4]);
            break;
          case "mobile":
            chart.updateSeries([45.1, 27.5, 8.4, 2.4]);
            break;
          default:
            chart.updateSeries([55.1, 28.5, 1.4, 5.4]);
        }
      } else {
        chart.updateSeries([35.1, 23.5, 2.4, 5.4]);
      }
    }

    // Attach the event listener to each checkbox
    checkboxes.forEach((checkbox) => {
      checkbox.addEventListener("change", (event) =>
        handleCheckboxChange(event, chart)
      );
    });
  }
}

watch(species, async (newValue) => {
  console.log("species changed from donut chart", newValue);

  const countMap: Map<string, number> = new Map();
  species.value.forEach((str) => {
    countMap.set(str, (countMap.get(str) || 0) + 1);
  });

  const data = Array.from(countMap).map(async ([name, value]) => {
    const client = useSupabaseClient<Database>();
    const { data, error } = await client
      .from("species")
      .select("*")
      .eq("id", name)
      .single();

    console.log("data from supabase", data, error);

    return { name: data!.common_name, value, color: "#4C51BF" };
  });

  const result = await Promise.all(data);

  chartData.value = result;

  if (chartRef) {
    chartRef.updateOptions(getChartOptions());
  }
});

onMounted(() => {
  initFlowbite();
  refreshData();
});
</script>

<style lang="scss" scoped></style>
